-- Seed sample albums for testing lists feature
-- Run this after the migration

INSERT INTO public.albums (title, artist, cover_url) VALUES
('Rumours', 'Fleetwood Mac', null),
('The Dark Side of the Moon', 'Pink Floyd', null),
('Abbey Road', 'The Beatles', null),
('Thriller', 'Michael Jackson', null),
('Back in Black', 'AC/DC', null),
('The Wall', 'Pink Floyd', null),
('Led Zeppelin IV', 'Led Zeppelin', null),
('Nevermind', 'Nirvana', null),
('Born to Run', 'Bruce Springsteen', null),
('Purple Rain', 'Prince', null),
('In Rainbows', 'Radiohead', null),
('OK Computer', 'Radiohead', null),
('The Queen Is Dead', 'The Smiths', null),
('London Calling', 'The Clash', null),
('Blue', 'Joni Mitchell', null),
('What''s Going On', 'Marvin Gaye', null),
('Songs in the Key of Life', 'Stevie Wonder', null),
('The Velvet Underground & Nico', 'The Velvet Underground', null),
('Blonde on Blonde', 'Bob Dylan', null),
('Pet Sounds', 'The Beach Boys', null),
('Aja', 'Steely Dan', null),
('The Rise and Fall of Ziggy Stardust', 'David Bowie', null),
('Graceland', 'Paul Simon', null),
('Remain in Light', 'Talking Heads', null),
('Illmatic', 'Nas', null),
('The Miseducation of Lauryn Hill', 'Lauryn Hill', null),
('To Pimp a Butterfly', 'Kendrick Lamar', null),
('good kid, m.A.A.d city', 'Kendrick Lamar', null),
('The College Dropout', 'Kanye West', null),
('My Beautiful Dark Twisted Fantasy', 'Kanye West', null),
('Channel Orange', 'Frank Ocean', null),
('Blonde', 'Frank Ocean', null),
('The Suburbs', 'Arcade Fire', null),
('Funeral', 'Arcade Fire', null),
('Is This It', 'The Strokes', null),
('Whatever People Say I Am, That''s What I''m Not', 'Arctic Monkeys', null),
('Turn On the Bright Lights', 'Interpol', null),
('Graduation', 'Kanye West', null),
('The Blueprint', 'Jay-Z', null),
('Ready to Die', 'The Notorious B.I.G.', null),
('Reasonable Doubt', 'Jay-Z', null),
('Enter the Wu-Tang (36 Chambers)', 'Wu-Tang Clan', null),
('The Chronic', 'Dr. Dre', null),
('All Eyez on Me', '2Pac', null),
('Doggystyle', 'Snoop Dogg', null),
('The Marshall Mathers LP', 'Eminem', null),
('The Eminem Show', 'Eminem', null),
('Stankonia', 'OutKast', null),
('Aquemini', 'OutKast', null),
('ATLiens', 'OutKast', null)
ON CONFLICT (title, artist) DO NOTHING;
